# Generated by Django 3.2.25 on 2026-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default=6, max_length=50),
            preserve_default=False,
        ),
    ]
