# Generated by Django 3.2.25 on 2026-02-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_enrollments_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('not_started', 'Not Started Yet'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.enrollments')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
            options={
                'unique_together': {('enrollment',)},
            },
        ),
    ]
