# Generated by Django 3.2.25 on 2026-02-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
    ]
