# Generated by Django 3.2.25 on 2026-02-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_lessonprogress_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
    ]
