# Generated by Django 3.2.25 on 2026-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[(1, 'Teacher'), (2, 'Student'), (3, 'Admin staff')], default='Student', max_length=50),
        ),
    ]
